server:
  port: 1989
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: culturapp
  datasource:
    url:  jdbc:h2:./devdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      url:  jdbc:h2:./devdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
      platform: h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: DEBUG