name: Continuous Deployment (DEV Environment)

on:
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  check-source-branch:
    name: Check source branch syntax
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Use github actions. "
        uses: actions/checkout@v2
      - name: "Check source branch syntax is OK"
        if: ${{ startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'fix/') }}
        run: |
          echo "Source branch OK. "
          exit 0
      - name: "Check source branch syntax is OK"
        if: ${{ !startsWith(github.head_ref, 'feature/') && !startsWith(github.head_ref, 'fix/') }}
        run: |
          echo "Incorrect source branch name, please check branching model strategy in confluence. "
          exit 1
  deploy-to-dev:
    needs: check-source-branch
    name: Push docker image to azure registry
    env:
      repo-name: 'f1rst-log-service'
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Generate Binary Distribution'
        run: |
          ./gradlew clean bootJar
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        id: image
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.repo-name }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.repo-name }}:${{ github.sha }}
          VERSION=${{ github.sha }}
          echo "::set-output name=version::${{ github.sha }}"
  update-software-deployments:
    needs: deploy-to-dev
    name: Update Software deployments
    env:
      repo-name: 'software-deployments'
    runs-on: ubuntu-latest
    steps:        
      - name: Check out Software Deployments
        uses: actions/checkout@main
        with:
          repository: OnLab-by-Santander/software-deployments
          token: ${{ secrets.SOFTWARE_DEPLOYMENTS_TOKEN }}    
      - name: 'Echo sha'
        run: |
          echo ${{ github.sha }}
      - name: 'Echo Files'
        run: |
          ls -la /home/runner/work/
          ls -la /home/runner/work/f1rst-log-service/
          ls -la /home/runner/work/f1rst-log-service/f1rst-log-service/    
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'services/f1rst-log-service/values.yaml'
          propertyPath: $['ob-chart']['image']['tag']
          value: ${{ github.sha }}
          branch: main
          targetBranch: main
          createPR: false
          masterBranchName: main
          updateFile: true
          token: ${{ secrets.SOFTWARE_DEPLOYMENTS_TOKEN }}
          message: 'Update Image Version to ${{ github.sha }}'
          repository: OnLab-by-Santander/software-deployments
      - name: 'Cat Files'
        run: |
          cat /home/runner/work/f1rst-log-service/f1rst-log-service/services/f1rst-log-service/values.yaml    
  slackNotification:
    needs: deploy-to-dev
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: onboarding-code-review
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=280&v=4
          SLACK_MESSAGE: 'Deployed to DEV environment'
          SLACK_TITLE: Deployed to DEV environment
          SLACK_USERNAME: DevOps-Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
